spring:
  application:
    name: rabbitmq-001
  rabbitmq:
    host: 192.168.127.131 # 默认主机
    port: 5672 # 默认端口
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: test # 虚拟主机
    publisher-returns: true # 开启消息发送失败返回队列
my:
  exchange: exchange.return.1
  queue: queue.return.1
  routing-key: routing.return.1

