spring:
  application:
    name: rabbitmq-003-delay1
  rabbitmq:
    host: 192.168.127.131 # \u9ED8\u8BA4\u4E3B\u673A
    port: 5672 # \u9ED8\u8BA4\u7AEF\u53E3
    username: admin # \u7528\u6237\u540D
    password: 123456 # \u5BC6\u7801
    virtual-host: test # \u865A\u62DF\u4E3B\u673A
my:
  exchange-delay-name: exchange.delay.2
  queue-delay-name: queue.delay.2
  delay-routing-key: delay.normal.2

