spring:
  application:
    name: rabbitmq-001
  rabbitmq:
    host: 192.168.127.131 # 默认主机
    port: 5672 # 默认端口
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: test # 虚拟主机



my:
  exchangeNormalName: exchange.normal.alternate
  exchangeAlternateName: exchange.alternate.1
  queueNormalName: queue.normal.alternate
  queueAlternateName: queue.alternate.1
