spring:
  application:
    name: rabbitmq-001
  rabbitmq:
    host: 192.168.127.131 # \u9ED8\u8BA4\u4E3B\u673A
    port: 5672 # \u9ED8\u8BA4\u7AEF\u53E3
    username: admin # \u7528\u6237\u540D
    password: 123456 # \u5BC6\u7801
    virtual-host: test # \u865A\u62DF\u4E3B\u673A
    publisher-confirm-type: correlated # \u5F00\u542F\u786E\u8BA4\u6A21\u5F0F


my:
  exchange: exchange.confirm.1
  queue: queue.confirm.1
  routing-key: confirm.1